version: "3.8"

services:
  db:
    image: postgres:15-alpine
    container_name: my_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./cars_driver_sample_data.sql:/cars_driver_sample_data.sql
      - ./cars_car_sample_data.sql:/cars_car_sample_data.sql
    environment:
      - POSTGRES_DB=carsdb
      - POSTGRES_USER=carsadmin
      - POSTGRES_PASSWORD=carspass
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U carsadmin -d carsdb || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 5s

  web:
    build: .
    container_name: my_django
    volumes:
      - static_data:/app/static
    environment:
      - SECRET_KEY=aboba-insecure
      - DEBUG=1
      - DB_NAME=carsdb
      - DB_USER=carsadmin
      - DB_PASSWORD=carspass
      - DB_HOST=db
      - DB_PORT=5432
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    ports:
      - "5000:5000"
    command: >
      sh -c "
        python manage.py makemigrations &&
        python manage.py migrate &&
        python manage.py collectstatic --noinput &&
        python manage.py runserver 0.0.0.0:5000
      "

volumes:
  postgres_data:
  static_data:

