FROM alpine:3.17

RUN apk update && \
    apk add --no-cache git && \
    rm -rf /var/cache/apk/* && \
    adduser -D appuser

COPY --from=gitfame-build /gitfame /usr/local/bin/gitfame
RUN chown appuser:appuser /usr/local/bin/gitfame

USER appuser

WORKDIR /repo
    
ENTRYPOINT ["gitfame"]
